### ISSUE TITLE
Example with classes?

### ISSUE THREAD

**Issue by SteveDeWald** [skovy/cooky-cutter#31]
I'm wondering how you would recommend using `cooky-cutter` with class models instead of interfaces?

Here's a simple example of a model:

```ts
// models/User.ts

class User {
  id?: number;
  name?: string;
  save = () => { /* ... */ };
}
export default User;
```

Here's what I would like to do:
```ts
// factories/user.ts

import { define, random } from "cooky-cutter";
import User from "../models/User";

const user = define<User>({
  id: random,
  name: (i: number) => `User #${i}`
})
```

However I get this error:
> Property 'save' is missing in type '{ id: () => number; name: (i: number) => string; }' but required in type 'Config<User>'.

This specific example would be pretty easy to make work, but you could imagine a more complex model with many methods.

Thanks.

**Comment by skovy** [comment]
Thanks for all of the details and examples @SteveDeWald. I hadn't considered classes before but it should continue to work as expected.

The intention behind `cooky-cutter` is that when the interface/class/thing being mocked changes and it's a breaking change, the compiler should throw a type error for the respective factory so it must be fixed. This helps ensure test data matches the actual expected data and not allow any drift in the difference between the two.

Since `save` is a required field on the `User` class, this type error is expected so I will be closing this issue since it's working as expected.

However, if you want to intentionally lose some of this type safety, there are two quick options I can think of:

**Mark the `save` attribute as optional**

I would recommend adding the `save` attribute to the factory since it's required in the class but if that's not possible, this may be one option. Depending on your configuration, you may also now get an error: `Cannot invoke an object which is possibly 'undefined'` when doing something like `user.save()`.

```ts
class User {
  id?: number;
  name?: string;
  save? = () => { /* ... */ };
}
```

**Mark all attributes as optional**

I would consider this a more aggressive approach because _all_ fields will be optional which is probably not what you want for the reasons stated above.

```ts
const user = define<Partial<User>>({
  id: random,
  name: (i: number) => `User #${i}`
})
```

Hopefully, this helps or let me know if I've misunderstood the question. Thanks again for the details and example!
